import { Data } from 'effect';
import {
  BuildInput,
  BuildOp_AttrsEntry,
  BuildOp_InputsEntry,
  BuildOp,
  CacheOpt,
  CDIDevice,
  ChownOpt,
  Definition_MetadataEntry,
  Definition,
  DiffOp,
  ExecOp,
  ExportCache,
  FileAction,
  FileActionCopy,
  FileActionMkDir,
  FileActionMkFile,
  FileActionRm,
  FileActionSymlink,
  FileOp,
  HostIP,
  Input,
  Location,
  Locations,
  LowerDiffInput,
  MergeInput,
  MergeOp,
  Meta,
  Mount,
  NamedUserOpt,
  Op,
  OpMetadata_CapsEntry,
  OpMetadata_DescriptionEntry,
  OpMetadata,
  Platform,
  Position,
  ProgressGroup,
  ProxyEnv,
  Range,
  SecretEnv,
  SecretOpt,
  Source_LocationsEntry,
  Source,
  SourceInfo,
  SourceOp_AttrsEntry,
  SourceOp,
  SSHOpt,
  TmpfsOpt,
  Ulimit,
  UpperDiffInput,
  UserOpt,
  WorkerConstraints,
} from './generated/ops.ts';

console.log('asd');

// Data.
